name: MuditFirstWf
on: [push, workflow_dispatch]
jobs:
  mudit-first-job:
   name: first job
   runs-on: ubuntu-latest
   steps:
    -  run: echo "trying my first workflow"
  second-job:
   needs: [mudit-first-job]
   name: second job
   runs-on: ubuntu-latest
   steps:
     -  run: echo "trying to run second job"