name: MuditFirstWf
on: [push, workflow_dispatch]
jobs:
  mudit-first-job:
   runs-on: ubuntu-latest
   steps:
    -  run: echo "trying my first workflow"
jobs:
   second-job:
    runs-on: ubuntu-latest
    steps:
     -  run: echo "trying to run second job"